<?php

function eck_spb_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'eck' && $plugin_type == 'property_behavior') {
    //This is a folder relative to our module. So we are stroing our property behavior plugins in 
    //a folder called property_behavior which is the plugin type's name. In ECK we stared the plugins in a 
    //directory under the plugins directory, you can look at eck.module to see the differences in the 
    //hook_ctools_plugin_directory implementation.  
    return $plugin_type;
  }
}

