<?php 

/**
 * Implementation of hook_eck_property_info()
 * 
 * The purpose of this hook is to declare a property that
 * can be used when creating an ECK entity type, it gives
 * a machine name for the property, and label, and the schema
 * for the property.
 * 
 */
function eck_property_uuid_eck_property_info(){
  $info = array();
  
  $info['uuid'] =
  array( 
    'label' => "UUID",
    'schema' =>
    array(
      'description' => 'The Universally Unique Identifier.',
      'type' => 'char',
      'length' => 36,
      'not null' => TRUE,
      'default' => '',
    )
  );
  
  return $info;
}