<?php 

/**
 * Implementation of hook_eck_property_info()
 * 
 * The purpose of this hook is to declare a property that
 * can be used when creating an ECK entity type, it gives
 * a machine name for the property, and label, and the schema
 * for the property.
 * 
 */
function eck_property_title_eck_property_info(){
  $info = array();
  
  $info['title'] = 
  array(
    'label' => "Title",
    'schema' =>
    array(
      'description' => 'The title is always treated as non-markup plain text.',
      'type' => 'varchar',
      'length' => 255,
      'not null' => TRUE,
      'default' => '',
    )
  );
  
  return $info;
}

function eck_property_title_entity_property_title_info_alter(&$info){
  //dpm($info, "Title alter Info");
  $info['widget'] = 'eck_property_title_widget';
}

function eck_property_title_widget($entity){
  $widget = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => isset($entity->title)?$entity->title:" ",
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  return $widget;
}

function eck_property_title_widget_submit($entity, $value){
  //dpm($value, "Title Submit");
  $entity->title = $value;
}
